name: PyInstaller

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: Install MinGW using Conda
      shell: bash
      run: $CONDA/Scripts/conda install m2w64-gcc libpython
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==3.6 
        python install_dependencies.py
    - name: build with pyinstaller
      run: |
        pyinstaller main_gui.py
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
      # Artifact name
        #name: # optional, default is artifact
      # A file, directory or wildcard pattern that describes what to upload
        path: dist/
      # The desired behavior if no files are found using the provided path.
